const fs=require('fs'),vm=require('vm'),assert=require('assert');
const elements=new Map();const el=s=>{if(!elements.has(s))elements.set(s,{value:'',innerHTML:'',textContent:'',hidden:false,classList:{toggle(){},add(){},remove(){}},addEventListener(){},showModal(){},close(){}});return elements.get(s)};
const context={console,Date,URL,Blob,Set,Map,JSON,crypto:require('crypto').webcrypto,setTimeout,clearTimeout,localStorage:{getItem(){return null},setItem(){}},document:{querySelector:el,querySelectorAll(){return []},addEventListener(){}}};vm.createContext(context);
vm.runInContext(fs.readFileSync('dist/data.js','utf8')+'\n'+fs.readFileSync('dist/prices.js','utf8')+'\n'+fs.readFileSync('dist/returns.js','utf8')+'\n'+fs.readFileSync('dist/clusters.js','utf8')+'\n'+fs.readFileSync('dist/app.js','utf8'),context);
const run=s=>vm.runInContext(s,context);
assert.equal(run('data.length'),47);assert.equal(run('new Set(data.map(r=>r.id)).size'),47);
run('data.forEach(validate)');
assert.equal(run('lag(SEED[0])'),28);assert.equal(run('lag(SEED[2])'),24);
assert.equal(run('parseCSV(csv(SEED)).length'),48);
assert.equal(run('parseCSV(csv([{...SEED[0],notes:\'comma, quote " and \\n newline\'}]))[1][13]'),'comma, quote " and \n newline');
assert.throws(()=>run('validate({...SEED[0],source:"javascript:alert(1)"})'));
assert.throws(()=>run('validate({...SEED[0],traded:"2026-02-30"})'));
assert.throws(()=>run('validate({...SEED[0],filed:"2020-01-01"})'));
assert.throws(()=>run('validate({...SEED[0],chamber:"unknown"})'));
run("clear();$('#chamber').value='Senate';renderRows()");assert.equal(run('filtered().length'),5);
run("clear();$('#search').value='Bloom Energy';renderRows()");assert.equal(run('filtered().length'),4);
run("clear();scope='following';renderRows()");assert.equal(run('filtered().length'),0);
run("follows.add('Nancy Pelosi');renderRows()");assert.equal(run('filtered().length'),14);
assert.ok(run('esc("<script>")').includes('&lt;'));
for(const asset of ['styles.css','app.js','data.js'])assert.ok(fs.existsSync('dist/'+asset));
console.log('Passed: seed integrity, date/URL validation, CSV round-trip, filters, watchlist and HTML escaping.');

run("clear();$('#chamber').value='Executive';renderRows()");assert.equal(run('filtered().length'),8);assert.equal(run('new Set(data.map(r=>r.person)).size'),8);assert.ok(run("card('Warren Davidson')").includes('+78.8%'));assert.ok(run("card('Donald Trump')").includes('Executive'));run("details(data.find(r=>r.person==='Donald Trump').id)");assert.ok(el('#detailContent').innerHTML.includes('Open Cabinet'));assert.ok(!el('#detailContent').innerHTML.includes('Coldpine'));
const fixture=(person,traded,extra={})=>({id:person+traded,person,traded,ticker:'TEST',asset:'Stock',type:'Purchase',...extra});
context.testRows=[fixture('A','2026-01-01'),fixture('A','2026-01-02',{owner:'Spouse'}),fixture('B','2026-01-31')];
assert.equal(run('buyingClusters(testRows,30)[0].count'),2);
assert.equal(run('buyingClusters(testRows.slice(0,2),30).length'),0);
context.testRows=[fixture('A','2026-01-01'),fixture('B','2026-01-31'),fixture('C','2026-03-02')];
assert.equal(run('buyingClusters(testRows,30).length'),2);
assert.ok(run('buyingClusters(testRows,30).every(g=>g.count===2)'));
context.testRows=[fixture('A','2026-01-01'),fixture('B','2026-02-01')];assert.equal(run('buyingClusters(testRows,30).length'),0);
context.testRows=[fixture('A','2026-01-01'),fixture('B','2026-01-01',{type:'Sale'}),fixture('C','2026-01-01',{type:'Exercise'}),fixture('D','2026-01-01',{asset:'ETF'})];assert.equal(run('buyingClusters(testRows,30).length'),0);
context.testRows=[fixture('A','2026-01-01'),fixture('B','2026-01-01',{asset:'Call options',ticker:'test'})];assert.equal(run('buyingClusters(testRows,7)[0].count'),2);
assert.equal(run('buyingClusters(SEED,30).length'),0);
run("data=[...SEED,{...SEED[0],id:'test-import',person:'Test Person',quality:'User-provided'}];clear();scope='clusters';renderRows()");
assert.equal(run('filtered().length'),5);assert.ok(el('#rows').innerHTML.includes('2 buyers'));
run('clusterDetails(0)');assert.ok(el('#detailContent').innerHTML.includes('User-provided'));
assert.ok(el('#detailContent').innerHTML.includes('Test Person'));
run("$('#clusterWindow').value='7';$('#clusterWindow').onchange()");assert.equal(run('clusterDays'),7);
run('data=[...SEED];clear()');assert.equal(run('clusters().length'),0);
console.log('Passed: unique households, inclusive boundaries, non-chained windows, excluded trades, calls, import flags, detail evidence and window control.');
assert.ok(run('data.filter(r=>r.type!=="Sale").every(r=>priceReturn(r)!==null)'));
assert.ok(Math.abs(run('priceReturn(SEED[0]).pct')-56.14689965)<0.0001);
assert.ok(run('priceCells(SEED[1])').includes('stock only'));
assert.equal(run('priceReturn(data.find(r=>r.type==="Sale"))'),null);
assert.equal(run('priceReturn({...SEED[0],ticker:"MISSING"})'),null);
assert.equal(run('priceReturn({...SEED[0],traded:"2026-07-25"})'),null);
assert.ok(run('returnDetails(SEED[1])').includes('not the option'));
run("clear();$('#type').value='Buys';$('#sort').value='upside';renderRows()");
assert.ok(run('filtered().every(r=>r.type!=="Sale")'));
assert.ok(run('filtered().every((r,i,a)=>!i||priceReturn(a[i-1]).pct>=priceReturn(r).pct)'));
assert.equal(run('filtered()[0].ticker'),'BE');
assert.ok(el('#rows').innerHTML.includes('+73.0%'));
assert.ok(run('Object.values(PRICES).every(p=>p.currency==="USD"&&p.asOf==="2026-09-25")'));
console.log('Passed: all purchase prices, benchmark arithmetic, option labels, missing dates, sales exclusion and gain sorting.');
const liveSource=fs.readFileSync('dist/live.js','utf8');
vm.runInContext(liveSource,context);
run("liveFeeds.congress=[{...SEED[0],id:'feed-duplicate',quality:'Feed summary'},{...SEED[0],id:'feed-new',person:'Another Member',filed:'2026-08-22'}];rebuildLiveData()");
assert.equal(run('data.length'),48);assert.equal(run('data.filter(r=>r.id==="feed-duplicate").length'),0);assert.equal(run('clusters().length'),1);
run("liveStatus.congress={checkedAt:Date.now(),value:{sourceUpdatedAt:'2026-09-20',rows:[],coverage:'Limited feed'},providerStale:true};liveStatusView()");assert.ok(el('#feedStatus').innerHTML.includes('Provider data stale'));
assert.ok(el('.snapshot').title.includes('No unattended scheduled task'));
console.log('Passed: automatic feed merge, checked-row precedence, cluster recomputation and visible freshness status.');
