const fs=require('fs'),vm=require('vm'),assert=require('assert');
const elements=new Map();const el=s=>{if(!elements.has(s))elements.set(s,{value:'',innerHTML:'',textContent:'',hidden:false,classList:{toggle(){},add(){},remove(){}},addEventListener(){},showModal(){},close(){}});return elements.get(s)};
const context={console,Date,URL,Blob,Set,Map,JSON,crypto:require('crypto').webcrypto,setTimeout,clearTimeout,localStorage:{getItem(){return null},setItem(){}},document:{querySelector:el,querySelectorAll(){return []},addEventListener(){}}};vm.createContext(context);
vm.runInContext(fs.readFileSync('dist/roster.js','utf8')+'\n'+fs.readFileSync('dist/data.js','utf8')+'\n'+fs.readFileSync('dist/prices.js','utf8')+'\n'+fs.readFileSync('dist/returns.js','utf8')+'\n'+fs.readFileSync('dist/clusters.js','utf8')+'\n'+fs.readFileSync('dist/track-record.js','utf8')+'\n'+fs.readFileSync('dist/portfolio.js','utf8')+'\n'+fs.readFileSync('dist/app.js','utf8'),context);
const run=s=>vm.runInContext(s,context);
assert.equal(run('data.length'),14);assert.ok(run('data.every(r=>rosterName(r.person))'));run('data=[...SEED]');assert.equal(run('data.length'),47);assert.equal(run('new Set(data.map(r=>r.id)).size'),47);
run('data.forEach(validate)');
assert.equal(run('lag(SEED[0])'),28);assert.equal(run('lag(SEED[2])'),24);
assert.equal(run('parseCSV(csv(SEED)).length'),48);
assert.equal(run('parseCSV(csv([{...SEED[0],notes:\'comma, quote " and \\n newline\'}]))[1][13]'),'comma, quote " and \n newline');
assert.throws(()=>run('validate({...SEED[0],source:"javascript:alert(1)"})'));
assert.throws(()=>run('validate({...SEED[0],traded:"2026-02-30"})'));
assert.throws(()=>run('validate({...SEED[0],filed:"2020-01-01"})'));
assert.throws(()=>run('validate({...SEED[0],chamber:"unknown"})'));
run("clear();$('#chamber').value='Senate';renderRows()");assert.equal(run('filtered().length'),5);
run("clear();$('#search').value='Bloom Energy';renderRows()");assert.equal(run('filtered().length'),4);
run("clear();scope='following';renderRows()");assert.equal(run('filtered().length'),0);
run("follows.add('Nancy Pelosi');renderRows()");assert.equal(run('filtered().length'),14);
assert.ok(run('esc("<script>")').includes('&lt;'));
for(const asset of ['styles.css','app.js','data.js'])assert.ok(fs.existsSync('dist/'+asset));
console.log('Passed: seed integrity, date/URL validation, CSV round-trip, filters, watchlist and HTML escaping.');

run("clear();$('#chamber').value='Executive';renderRows()");assert.equal(run('filtered().length'),8);assert.equal(run('new Set(data.map(r=>r.person)).size'),8);assert.ok(run("card('Nancy Pelosi')").includes('2 / 2 years'));assert.ok(run("card('Donald Trump')").includes('Executive'));run("details(data.find(r=>r.person==='Donald Trump').id)");assert.ok(el('#detailContent').innerHTML.includes('Open Cabinet'));assert.ok(!el('#detailContent').innerHTML.includes('Coldpine'));
const fixture=(person,traded,extra={})=>({id:person+traded,person,traded,filed:traded,ticker:'TEST',asset:'Stock',type:'Purchase',...extra});
context.testRows=[fixture('A','2026-01-01'),fixture('A','2026-01-02',{owner:'Spouse'}),fixture('B','2026-01-31')];
assert.equal(run('buyingClusters(testRows,30)[0].count'),2);
assert.equal(run('buyingClusters(testRows.slice(0,2),30).length'),0);
context.testRows=[fixture('A','2026-01-01'),fixture('B','2026-01-31'),fixture('C','2026-03-02')];
assert.equal(run('buyingClusters(testRows,30).length'),2);
assert.ok(run('buyingClusters(testRows,30).every(g=>g.count===2)'));
context.testRows=[fixture('A','2026-01-01'),fixture('B','2026-02-01')];assert.equal(run('buyingClusters(testRows,30).length'),0);
context.testRows=[fixture('A','2026-01-01'),fixture('B','2026-01-01',{type:'Sale'}),fixture('C','2026-01-01',{type:'Exercise'}),fixture('D','2026-01-01',{asset:'ETF'})];assert.equal(run('buyingClusters(testRows,30).length'),0);
context.testRows=[fixture('A','2026-01-01'),fixture('B','2026-01-01',{asset:'Call options',ticker:'test'})];assert.equal(run('buyingClusters(testRows,7)[0].count'),2);
assert.equal(run('buyingClusters(SEED,30).length'),0);
assert.equal(run("buyingClusters([...SEED,{...SEED[0],id:'test-import',person:'Test Person',quality:'User-provided'}],30).length"),0);
run("signalData=[...SEED,{...SEED[0],id:'test-other',person:'Test Person',quality:'Feed summary'}];data=selectedRecords(signalData);clear();scope='clusters';renderRows()");
assert.equal(run('filtered().length'),4);assert.ok(el('#rows').innerHTML.includes('2 buyers'));
run('clusterDetails(0)');assert.ok(el('#detailContent').innerHTML.includes('Feed summary'));
assert.ok(el('#detailContent').innerHTML.includes('Test Person'));
run("$('#clusterWindow').value='7';$('#clusterWindow').onchange()");assert.equal(run('clusterDays'),7);
run('signalData=[...SEED];data=[...SEED];clear()');assert.equal(run('clusters().length'),0);
console.log('Passed: unique households, inclusive boundaries, non-chained windows, excluded trades, calls, import exclusion, unfeatured households, detail evidence and window control.');
assert.ok(run('data.filter(r=>r.type!=="Sale").every(r=>priceReturn(r)!==null)'));
assert.ok(Math.abs(run('priceReturn(SEED[0]).pct')-56.14689965)<0.0001);
assert.ok(run('priceCells(SEED[1])').includes('stock only'));
assert.equal(run('priceReturn(data.find(r=>r.type==="Sale"))'),null);
assert.equal(run('priceReturn({...SEED[0],ticker:"MISSING"})'),null);
assert.equal(run('priceReturn({...SEED[0],traded:"2026-07-25"})'),null);
assert.ok(run('returnDetails(SEED[1])').includes('not the option'));
run("clear();$('#type').value='Buys';$('#sort').value='upside';renderRows()");
assert.ok(run('filtered().every(r=>r.type!=="Sale")'));
assert.ok(run('filtered().every((r,i,a)=>!i||priceReturn(a[i-1]).pct>=priceReturn(r).pct)'));
assert.equal(run('filtered()[0].ticker'),'BE');
assert.ok(el('#rows').innerHTML.includes('+73.0%'));
assert.ok(run('Object.values(PRICES).every(p=>p.currency==="USD"&&p.asOf==="2026-09-25")'));
console.log('Passed: all purchase prices, benchmark arithmetic, option labels, missing dates, sales exclusion and gain sorting.');
const liveSource=fs.readFileSync('dist/live.js','utf8');
vm.runInContext(liveSource,context);
run("liveFeeds.congress=[{...SEED[0],id:'feed-duplicate',quality:'Feed summary'},{...SEED[0],id:'feed-new',person:'Tom Suozzi',filed:'2026-08-22'}];rebuildLiveData()");
assert.equal(run('data.length'),15);assert.equal(run('data.filter(r=>r.id==="feed-duplicate").length'),0);assert.equal(run('clusters().length'),1);
run("liveStatus.congress={checkedAt:Date.now(),value:{sourceUpdatedAt:'2026-09-20',rows:[],coverage:'Limited feed'},providerStale:true};liveStatusView()");assert.ok(el('#feedStatus').innerHTML.includes('Provider data stale'));
assert.ok(el('.snapshot').title.includes('Scheduled research status appears on Home'));
console.log('Passed: automatic feed merge, checked-row precedence, cluster recomputation and visible freshness status.');
run("data=[...SEED];clear();$('#search').value='Bloom Energy';renderRows()");
assert.ok(el('#rows').innerHTML.includes('Bought on'));
assert.ok(el('#rows').innerHTML.includes('Disclosed on'));
assert.ok(el('#rows').innerHTML.includes('28 days after trade'));
assert.ok(el('#rows').innerHTML.includes('Bloom Energy'));
assert.equal(run("disclosedDate(SEED.find(r=>r.person==='Donald Trump'))"),'2026-09-22');
assert.equal(run("disclosureDelay(SEED.find(r=>r.person==='Donald Trump'))"),53);
assert.equal(run("disclosedDate({...SEED[0],chamber:'Executive',source:'https://example.com/another.pdf'})"),null);
assert.equal(run("transactionLabel({type:'Sale'})"),'Sold on');
assert.equal(run("transactionLabel({type:'Exercise'})"),'Exercised on');
run("PRICES.TEST={latest:150,asOf:'2026-09-25',currency:'USD',source:'https://finance.yahoo.com/quote/TEST/history/',closes:{'2026-07-01':100,'2026-07-15':125}};");
assert.equal(run("disclosureReturn({...SEED[0],ticker:'TEST',traded:'2026-07-01',filed:'2026-07-15'}).pct"),19.999999999999996);
assert.equal(run("disclosureReturn({...SEED[0],ticker:'TEST',traded:'2026-07-01',filed:'2026-07-16'})"),null);
run("details(SEED.find(r=>r.person==='Donald Trump').id)");assert.ok(el('#detailContent').innerHTML.includes('Report signed'));assert.ok(el('#detailContent').innerHTML.includes('Sep 22, 2026'));
console.log('Passed: labeled dates, publication vs signature, disclosure gaps, company names and disclosure-day price calculations.');
const trackFixture=[{person:'A',ticker:'T',type:'Purchase',asset:'Stock',traded:'2026-09-01',filed:'2026-09-02',chamber:'House',source:'https://example.com'}, {person:'A',ticker:'LOSS',type:'Purchase',asset:'ETF',traded:'2026-09-01',filed:'2026-09-02',chamber:'House',source:'https://example.com'}];
const trackPrices={T:{latest:120,asOf:'2026-09-25',closes:{'2026-09-01':100,'2026-09-02':110}},LOSS:{latest:80,asOf:'2026-09-25',closes:{'2026-09-01':100,'2026-09-02':100}}};
context.trackFixture=trackFixture;context.trackPrices=trackPrices;
const tr=run("trackRecord('A',{basis:'trade',period:'all'},[...trackFixture,trackFixture[0],{...trackFixture[0],asset:'Call options'},{...trackFixture[0],ticker:'MISSING'}],trackPrices,Date.parse('2026-09-26'))");
assert.equal(tr.count,2);assert.equal(tr.total,3);assert.ok(Math.abs(tr.avg)<1e-8);assert.equal(tr.win,50);
const dr=run("trackRecord('A',{basis:'disclosed',period:'all'},trackFixture,trackPrices,Date.parse('2026-09-26'))");assert.ok(Math.abs(dr.avg-((120/110-1)*100-20)/2)<1e-8);
assert.equal(run("trackRecord('A',{basis:'trade',period:'90'},trackFixture,trackPrices,Date.parse('2027-09-26')).count"),0);
run("trackSettings.min=0;trackSettings.gain=0;renderPeople()");assert.ok(run("rankPeople([...new Set(data.map(r=>r.person))]).every(p=>trackRecord(p).avg>=0)"));
console.log('Passed: track-record dedupe, missing coverage, option exclusions, equal weighting, return bases, win rate, time window and gain filtering.');
vm.runInContext(fs.readFileSync('dist/terminal.js','utf8'),context);
for(const selector of ['#chartCrosshair','#chartFocus'])el(selector).setAttribute=()=>{};
run("signalData=[...SEED];data=selectedRecords(SEED);PRICES.BE.closes=Object.fromEntries(['2026-07-20','2026-07-21','2026-07-22','2026-07-23','2026-07-24','2026-07-27','2026-07-28','2026-07-29','2026-07-30','2026-08-21'].map((d,i)=>[d,100+i]));renderStockChart()");
assert.equal((el('#stockChart').innerHTML.match(/data-event-mode="traded"/g)||[]).length,2);
run("setChartOption('buys',false);setChartOption('disclosures',true)");
assert.ok(!el('#stockChart').innerHTML.includes('data-event-mode="traded"'));
assert.equal((el('#stockChart').innerHTML.match(/data-event-mode="disclosed"/g)||[]).length,1);
assert.equal(run("nearestChartIndex(Date.parse('2026-01-04'),[['2026-01-02',100],['2026-01-05',110]])"),1);
context.DOMPoint=class{constructor(x,y){this.x=x;this.y=y}matrixTransform(){return this}};
el('#stockChart svg').getScreenCTM=()=>({inverse(){return {}}});
run("inspectPointer({clientX:-100,clientY:30,pointerType:'touch',target:{closest(){return null}}})");
assert.equal(run('inspectedDate'),run('plottedPoints[0][0]'));
run("inspectPointer({clientX:2000,clientY:30,pointerType:'touch',target:{closest(){return null}}})");
assert.equal(run('inspectedDate'),run('plottedPoints.at(-1)[0]'));
assert.equal(run("selectedRecords([{person:'Donald Trump'},{person:'Thomas Suozzi'}])[0].person"),'Tom Suozzi');
assert.equal(run('Object.keys(ROSTER).length'),9);
console.log('Passed: independent chart layers, touch coordinate boundaries, nearest trading date and roster exclusions/aliases.');
vm.runInContext(fs.readFileSync('dist/home.js','utf8'),context);
context.homeRows=[{type:'Purchase',traded:'2026-01-01',filed:'2026-02-01'},{type:'Sale',traded:'2026-03-01',filed:'2026-03-02'},{type:'Purchase',traded:'2026-02-01',filed:'2026-02-03'}];
assert.equal(run('latestPurchases(homeRows).length'),2);assert.equal(run('latestPurchases(homeRows)[0].traded'),'2026-02-01');
assert.ok(run("miniChart({closes:{'2026-09-01':100,'2026-09-02':110}},'TEST')").includes('one month closing prices'));
assert.ok(run("miniChart({},'TEST')").includes('History unavailable'));
run('renderHome()');assert.ok(el('#accountControls').innerHTML.includes('/signin-with-chatgpt?return_to=%2F'));
run("workspaceState.user={email:'<script>@test'};renderAccount()");assert.ok(el('#accountControls').innerHTML.includes('&lt;script&gt;@test'));assert.ok(!el('#accountControls').innerHTML.includes('<script>'));
console.log('Passed: purchase ordering and exclusion, price-backed sparklines, sign-in links and account escaping.');
vm.runInContext(fs.readFileSync('dist/swing.js','utf8'),context);
const days=Array.from({length:220},(_,i)=>new Date(Date.UTC(2025,0,1+i)).toISOString().slice(0,10));
context.swingFixture={asOf:days.at(-1),closes:Object.fromEntries(days.map((d,i)=>[d,100+i])),bars:Object.fromEntries(days.map((d,i)=>[d,{high:102+i,low:98+i,volume:i===219?200:100}]))};
const tech=run('technicals(swingFixture)');assert.equal(tech.sma20,309.5);assert.equal(tech.sma200,219.5);assert.equal(tech.rsi,100);assert.equal(tech.atr,4);assert.equal(tech.relativeVolume,2);assert.equal(tech.priorHigh20,318);
assert.equal(run('relativeReturn(swingFixture,swingFixture,20)'),0);assert.equal(run('relativeReturn(swingFixture,{},20)'),null);
assert.equal(run('technicals({}).rsi'),null);assert.equal(run('technicals({}).atr'),null);
run('delete swingFixture.bars[Object.keys(swingFixture.bars).at(-5)]');assert.equal(run('technicals(swingFixture).atr'),null);
assert.equal(run('periodReturn({},5)'),null);
console.log('Passed: SMA windows, Wilder RSI/ATR, relative volume, prior-high exclusion, matched-date benchmark and missing-bar handling.');

const sessionDates=['2026-09-02','2026-09-03','2026-09-04','2026-09-07','2026-09-08','2026-09-09','2026-09-10'];
context.copyPrices={T:{latest:110,asOf:sessionDates.at(-1),closes:Object.fromEntries(sessionDates.map((d,i)=>[d,[50,100,120,90,100,105,110][i]]))},SPY:{closes:Object.fromEntries(sessionDates.map((d,i)=>[d,100+i]))}};
const copy=run("trackRecord('A',{basis:'disclosed',period:'all',horizon:'5'},[trackFixture[0],trackFixture[0],{...trackFixture[0],asset:'Call options'}],copyPrices,Date.parse('2026-09-26'))");
assert.equal(copy.count,1);assert.equal(copy.total,1);assert.ok(Math.abs(copy.avg-10)<1e-8);assert.equal(copy.win,100);assert.equal(copy.lag,1);assert.equal(copy.drawdown,-25);assert.equal(copy.benchmarkCount,1);assert.ok(Math.abs(copy.excess-(10-(106/101-1)*100))<1e-8);
assert.equal(run("trackRecord('A',{basis:'disclosed',period:'all',horizon:'20'},[trackFixture[0]],copyPrices,Date.parse('2026-09-26')).count"),0);
assert.equal(run("trackRecord('A',{basis:'disclosed',period:'all',horizon:'20'},[trackFixture[0]],copyPrices,Date.parse('2026-09-26')).pending"),1);
assert.equal(run("rosterName('Ron L Wyden')"),'Ron Wyden');assert.equal(run("rosterName('Richard L Scott')"),'Rick Scott');assert.ok(!run("rosterName('Austin Scott')"));assert.ok(!run("rosterName('Scott Franklin')"));
console.log('Passed: next-close entry, fixed forward window, immature exclusion, matched SPY, drawdown and distinct senator identities.');
const baseHolding={person:'Test',ticker:'ABC',company:'Example',asset:'Stock',owner:'Spouse',type:'Purchase',traded:'2026-01-02',filed:'2026-01-05',chamber:'House',source:'https://example.com/filing',amount:'$1,001-$15,000',quality:'Official filing'};
context.holdingsFixture=[baseHolding];
const portfolio=rows=>{context.holdingsFixture=rows;return run("inferredPortfolio('Test',holdingsFixture)")};
assert.equal(portfolio([baseHolding]).held.length,1);
assert.equal(portfolio([{...baseHolding,type:'Exercise'}]).held.length,1);
let result=portfolio([baseHolding,{...baseHolding,type:'Sale',traded:'2026-02-01',filed:'2026-02-03',notes:'Partial sale'}]);assert.equal(result.held.length,0);assert.equal(result.uncertain[0].status,'Sale disclosed; balance unknown');
assert.equal(portfolio([baseHolding,{...baseHolding,type:'Sale',traded:'2025-12-01',filed:'2026-03-01'}]).held.length,1);
assert.equal(portfolio([baseHolding,{...baseHolding,type:'Sale',owner:'Self',traded:'2026-02-01',filed:'2026-02-03'}]).held.length,1);
assert.equal(portfolio([baseHolding,{...baseHolding,type:'Sale',owner:'Not specified',asset:'Unclassified',traded:'2026-02-01',filed:'2026-02-03'}]).held.length,0);
assert.equal(portfolio([baseHolding,{...baseHolding,type:'Sale'}]).held.length,0);
assert.equal(portfolio([{...baseHolding,asset:'Call options'}]).held.length,0);
assert.equal(portfolio([{...baseHolding,quality:'User-provided'}]).held.length,0);
assert.equal(portfolio([{...baseHolding,traded:'2099-01-01',filed:'2099-01-02'}]).held.length,0);
assert.equal(portfolio([{...baseHolding,type:'Sale'}]).uncertain[0].status,'Sale only; balance unknown');
assert.equal(portfolio([baseHolding,baseHolding]).held.length,1);
assert.equal(run("inferredPortfolio('Nobody',[]).asOf"),undefined);
assert.ok(run("portfolioCard('Nobody')").includes('does not mean an empty portfolio'));
context.unsafeHolding={...portfolio([baseHolding]).held[0],company:'<script>bad</script>'};assert.ok(!run('portfolioRow(unsafeHolding)').includes('<script>'));
console.log('Passed: inferred holdings, exercises, partial/unknown-owner sales, same-day ambiguity, transaction chronology, options, incomplete history and escaping.');
context.followerRow={...trackFixture[0],ticker:'COPY',filed:'2026-09-04'};context.followerPrices={COPY:{latest:120,asOf:'2026-09-09',closes:{'2026-09-04':80,'2026-09-08':100,'2026-09-09':120}}};
let fr=run('followerReturn(followerRow,followerPrices)');assert.equal(fr.basisDate,'2026-09-08');assert.ok(Math.abs(fr.pct-20)<1e-8);
assert.equal(run("followerReturn({...followerRow,filed:'2026-09-09'},followerPrices)"),null);
assert.equal(run("followerReturn({...followerRow,type:'Sale'},followerPrices)"),null);
assert.equal(run("followerReturn({...followerRow,asset:'Call options'},followerPrices).underlying"),true);
run("followerPrices.COPY.latest=90");assert.ok(run('followerReturn(followerRow,followerPrices).pct')<0);
run("followerPrices.COPY.latest=100");assert.equal(run('followerReturn(followerRow,followerPrices).pct'),0);
assert.ok(fs.readFileSync('dist/index.html','utf8').includes('>Since disclosure</th>'));
run('renderHome()');assert.ok(el('#homePurchases').innerHTML.includes('home-disclosure-return'));
console.log('Passed: follower return excludes disclosure-day gains, handles missing trade-day history, market closures, missing next close, options, losses and zero return.');
el('#stockChart').clientWidth=360;
run("showBuyMarkers=true;showDisclosureMarkers=true;marketSymbol='BE';renderStockChart()");
assert.ok(el('#stockChart').innerHTML.includes('viewBox="0 0 360 300"'));
assert.ok(el('#stockChart').innerHTML.includes('class="marker-hit"'));assert.ok(el('#stockChart').innerHTML.includes('r="22"'));
assert.ok(el('#stockChart').innerHTML.includes('disclosure-marker'));assert.ok(el('#chartActivity').innerHTML.includes('Nancy Pelosi'));
assert.ok(el('#chartActivity').innerHTML.includes('Disclosed'));assert.ok(el('#chartActivity').innerHTML.includes('Bought'));
run("eventDetails('2026-08-21','disclosed')");assert.ok(el('#detailContent').innerHTML.includes('Since disclosure:'));
console.log('Passed: mobile-sized SVG, large hit targets, distinct disclosure markers, activity returns and tap detail returns.');
