import assert from 'node:assert/strict';
import {researchIngest,validNewsItem} from './server/research.mjs';
const now=new Date().toISOString().slice(0,10),item={category:'new',title:'Policy update',summary:'A sourced policy changed.',impact:'Costs could rise; scope remains uncertain.',risk:'Final scope may be narrower.',watch:'Final implementation date.',date:now,tickers:['INTC'],sources:['https://www.congress.gov/bill/test']};
assert(validNewsItem(item));assert(!validNewsItem({...item,risk:''}));assert(!validNewsItem({...item,tickers:[]}));assert(validNewsItem({...item,category:'context',date:new Date(Date.now()-14*86400000).toISOString().slice(0,10)}));assert(!validNewsItem({...item,category:'general',date:new Date(Date.now()-14*86400000).toISOString().slice(0,10)}));assert(!validNewsItem({...item,sources:['https://x.com/example/status/1']}));assert(!validNewsItem({...item,date:'2020-01-01'}));assert(!validNewsItem({...item,sources:['javascript:alert(1)']}));
const memory=new Map(),env={RESEARCH_INGEST_TOKEN:'test',BUCKET:{get:async k=>memory.has(k)?{json:async()=>JSON.parse(memory.get(k))}:null,put:async(k,v)=>memory.set(k,v)}};
const post=body=>researchIngest(new Request('http://test',{method:'POST',headers:{Authorization:'Bearer test','Content-Type':'application/json'},body:JSON.stringify(body)}),env);
assert.equal((await post({kind:'news',items:[item]})).body.published,1);
assert.equal((await post({kind:'news',items:[item]})).body.published,0);
await post({kind:'news',items:[],status:'failed'});
assert.equal(JSON.parse(memory.get('poor/research/news')).editions.length,1);
assert.equal(JSON.parse(memory.get('poor/research/news')).status,'Briefing update failed');
assert.equal((await post({kind:'news',items:Array.from({length:8},(_,i)=>({...item,title:'Distinct '+i,sources:['https://www.sec.gov/news/item-'+i]}))})).body.published,8);
assert.equal((await post({kind:'news',items:Array(9).fill(item)})).status,400);
console.log('Passed: fresh sourced news, X-only rejection, unsafe URLs, deduplication and archive preservation on failure.');
