import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import worker,{currentQuote} from './server/worker.mjs';
const now=Date.now(),meta={symbol:'VOO',currency:'USD',regularMarketPrice:605,regularMarketTime:Math.floor(now/1000)-10,chartPreviousClose:600,currentTradingPeriod:{regular:{start:Math.floor(now/1000)-3600,end:Math.floor(now/1000)+3600}}},raw={chart:{result:[{meta}]}};
assert.equal(currentQuote(raw,'VOO',now).latest,605);assert.equal(currentQuote(raw,'VOO',now).marketOpen,true);
assert.equal(currentQuote(raw,'VOO',now).previousClose,600);
assert.equal(currentQuote(raw,'VOO',now+4000000).marketOpen,false);
assert.equal(currentQuote(raw,'VOO',now+300000).delayed,true);
assert.throws(()=>currentQuote(raw,'SPY',now));assert.throws(()=>currentQuote({chart:{result:[{meta:{...meta,regularMarketPrice:NaN}}]}},'VOO',now));
const store=new Map(),env={BUCKET:{get:async k=>store.has(k)?{etag:'v',json:async()=>JSON.parse(store.get(k))}:null,put:async(k,v)=>{store.set(k,v);return {etag:'v'}}}};
let calls=0,fail=false;globalThis.fetch=async()=>{calls++;if(fail)throw Error('Provider down');return new Response(JSON.stringify(raw))};
const request=async suffix=>(await worker.fetch(new Request('https://poor.test/api/quotes?symbols=VOO'+suffix),env)).json();
assert.equal((await request('')).VOO.value.latest,605);await request('');assert.equal(calls,1);
await request('&refresh=1');assert.equal(calls,2);fail=true;const stale=await request('&refresh=1');assert.equal(stale.VOO.value.latest,605);assert.equal(stale.VOO.stale,true);
assert.equal((await worker.fetch(new Request('https://poor.test/api/quotes?symbols=../secret'),env)).status,400);
const nodes=new Map(),get=s=>{if(!nodes.has(s))nodes.set(s,{classList:{toggle:()=>{}},setAttribute:()=>{}});return nodes.get(s)},events={},requests=[],timers=[];
const ctx=vm.createContext({console,Date,Set,Map,Number,Math,Promise,encodeURIComponent,PRICES:{VOO:{currency:'USD',latest:600,asOf:'2026-09-25',closes:{'2026-09-25':600}}},read:(k,d)=>d,persist:()=>{},marketSymbol:'VOO',workspaceState:{symbols:['VOO']},view:'market',tickerValid:s=>/^[A-Z]+$/.test(s),$:get,stamp:x=>x,date:x=>x,document:{hidden:false,addEventListener:(n,fn)=>events[n]=fn,createElement:()=>({setAttribute:()=>{}}),querySelector:()=>null},setTimeout:(fn,ms)=>{timers.push(ms);return timers.length},clearTimeout:()=>{},renderTerminal:()=>{},getLiveJSON:async u=>{requests.push(u);return {VOO:{value:currentQuote(raw,'VOO',now),checkedAt:now}}}});
get('#appUtilityMenu').append=()=>{};get('#commandButton').before=()=>{};
vm.runInContext(fs.readFileSync('dist/quotes.js','utf8'),ctx);events.DOMContentLoaded();await vm.runInContext('quoteRunning',ctx);
assert.ok(requests[0].includes('refresh=1'));assert.equal(timers.at(-1),30000);
assert.equal(vm.runInContext('displayQuote("VOO").latest',ctx),605);assert.equal(ctx.PRICES.VOO.latest,600);assert.equal(ctx.PRICES.VOO.closes['2026-09-25'],600);
get('#quoteSeconds').onchange({target:{value:'60'}});assert.equal(timers.at(-1),60000);
get('#quoteAuto').onchange({target:{checked:false}});assert.equal(get('#quoteSeconds').disabled,true);
const count=requests.length;events.visibilitychange();assert.equal(requests.length,count);
get('#quoteRefresh').onclick();await vm.runInContext('quoteRunning',ctx);assert.equal(requests.length,count+1);assert.ok(requests.at(-1).includes('refresh=1'));
console.log('Passed: current quotes, trading status, provider timestamps, forced refresh, cache reuse, stale fallback, invalid symbols, 30/60s preference, auto off, manual/reload refresh and immutable historical closes.');
