// Public-source research. Independent caches keep a failed provider from hiding other evidence.
const RHOUR=3600000;
const researchUniverse={BE:['Bloom Energy','fuel cells'],INTC:['Intel','semiconductors'],NVDA:['NVIDIA','semiconductors'],AMD:['Advanced Micro Devices','semiconductors'],AAPL:['Apple','consumer electronics'],MSFT:['Microsoft','cloud computing'],AMZN:['Amazon','cloud computing'],GOOG:['Alphabet','artificial intelligence'],GOOGL:['Alphabet','artificial intelligence'],META:['Meta Platforms','social media'],TSLA:['Tesla','electric vehicles'],AVGO:['Broadcom','semiconductors'],LMT:['Lockheed Martin','defense'],RTX:['RTX','defense'],PLTR:['Palantir','artificial intelligence']};
const cleanXML=s=>String(s||'').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").trim();
const xt=(s,t)=>cleanXML(new RegExp('<'+t+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+t+'>','i').exec(s)?.[1]);
const blocks=(s,t)=>[...s.matchAll(new RegExp('<'+t+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+t+'>','gi'))].map(m=>m[1]);
const day=s=>/^\d{4}-\d{2}-\d{2}$/.test(s||'')&&!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;
const num=s=>s!==''&&Number.isFinite(Number(s))?Number(s):null;
let secNextRequest=0;
const today=()=>new Date().toISOString().slice(0,10);
const ago=n=>new Date(Date.now()-n*86400000).toISOString().slice(0,10);
async function researchFetch(url,opts={}){if(new URL(url).hostname.endsWith('sec.gov')){const delay=Math.max(0,secNextRequest-Date.now());secNextRequest=Date.now()+delay+150;if(delay)await new Promise(resolve=>setTimeout(resolve,delay))}const r=await fetch(url,{...opts,headers:{'User-Agent':'poor public financial research https://poor.daaalil.chatgpt.site','Accept':'application/json, application/xml, text/csv',...opts.headers},signal:AbortSignal.timeout(18000)});if(!r.ok)throw Error('Provider returned '+r.status);const text=await r.text();if(text.length>8000000)throw Error('Source response exceeds limit');return text}
const rjson=async(url,opts)=>JSON.parse(await researchFetch(url,opts));
export function parseForm4(xml,{url,accepted,accession,symbol}){
 if(!xml.includes('<ownershipDocument'))throw Error('Invalid Form 4 XML');
 const issuer=xt(xml,'issuerTradingSymbol').toUpperCase();if(issuer!==symbol)throw Error('Issuer ticker mismatch');
 const amended=xt(xml,'documentType')==='4/A',owners=blocks(xml,'reportingOwner').map(o=>({name:xt(o,'rptOwnerName'),id:xt(o,'rptOwnerCik'),role:xt(o,'officerTitle')|| (xt(o,'isDirector')==='1'?'Director':xt(o,'isTenPercentOwner')==='1'?'10% owner':'Reporting owner')}));
 return blocks(xml,'nonDerivativeTransaction').map((t,i)=>{const traded=xt(t,'transactionDate'),shares=num(xt(t,'transactionShares')),price=num(xt(t,'transactionPricePerShare')),code=xt(t,'transactionCode');return {id:'sec:'+accession+':'+i,kind:'insider',symbol,title:owners.map(o=>o.name).join(' / '),owners,role:owners.map(o=>o.role).join(' / '),code,purchase:code==='P'&&xt(t,'transactionAcquiredDisposedCode')==='A'&&!amended,traded,published:accepted||null,url,amended,plan10b51:xt(xml,'aff10b5One')==='1',shares,price,amount:shares!==null&&price!==null?shares*price:null,security:xt(t,'securityTitle'),ownership:xt(t,'directOrIndirectOwnership'),match:'SEC issuer ticker',note:amended?'Amendment · excluded from signals':code==='P'?'Open-market or private purchase':({A:'Award / grant',M:'Exercise / conversion',F:'Tax withholding',S:'Sale',G:'Gift'}[code]||'Other transaction')};}).filter(r=>day(r.traded)&&r.traded<=today());
}
export function parseTreasury(xml){
 const rows=blocks(xml,'m:properties').map(x=>({date:xt(x,'d:NEW_DATE').slice(0,10),m3:num(xt(x,'d:BC_3MONTH')),y2:num(xt(x,'d:BC_2YEAR')),y10:num(xt(x,'d:BC_10YEAR')),y30:num(xt(x,'d:BC_30YEAR'))})).filter(x=>day(x.date)&&x.date<=today()&&x.y10!==null).sort((a,b)=>a.date.localeCompare(b.date));
 if(!rows.length)throw Error('No Treasury yield observations');return {rows:rows.slice(-65),url:'https://home.treasury.gov/resource-center-data-chart-center/interest-rates',unit:'percent',source:'US Treasury daily par yield curve'};
}
export function parseCalendar(csv){const rows=[];let row=[],value='',quoted=false;for(let i=0;i<csv.length;i++){const c=csv[i];if(c==='"'){if(quoted&&csv[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(!quoted&&(c===','||c==='\n')){row.push(value.replace(/\r$/,''));value='';if(c==='\n'){rows.push(row);row=[]}}else value+=c}if(value||row.length){row.push(value.trim());rows.push(row)}const h=rows.shift()||[];if(!h.includes('reportDate')||!h.includes('symbol'))throw Error('Earnings calendar unavailable or quota exceeded');return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]]))).filter(r=>day(r.reportDate));}
async function observed(env,symbol,source,result){
 const path='poor/research/observed/'+symbol+'/'+source,old=await env.BUCKET.get(path),known=old?await old.json():{},now=new Date().toISOString();
 result.items=(result.items||[]).map(item=>({...item,firstObserved:known[item.id]||now}));
 const next=Object.fromEntries(result.items.map(i=>[i.id,i.firstObserved]));await env.BUCKET.put(path,JSON.stringify({...known,...next}));return result;
}
async function secResearch(env,symbol,cache){
 const mapping=await cache(env,'sec-tickers',24*RHOUR,()=>rjson('https://www.sec.gov/files/company_tickers.json'));if(!mapping.value)throw Error('SEC company directory unavailable');
 const issuer=Object.values(mapping.value).find(v=>v.ticker===symbol);if(!issuer)return {items:[],coverage:'No SEC issuer match for this ticker'};
 const cik=String(issuer.cik_str).padStart(10,'0'),s=await rjson('https://data.sec.gov/submissions/CIK'+cik+'.json'),recent=s.filings?.recent;if(!recent?.form)throw Error('SEC filing index unavailable');
 const filings=recent.form.map((f,i)=>({form:f,accession:recent.accessionNumber[i],doc:recent.primaryDocument[i],accepted:recent.acceptanceDateTime[i],filed:recent.filingDate[i]})).filter(f=>['4','4/A'].includes(f.form)&&f.filed>=ago(180)).slice(0,20);
 const items=[],errors=[];for(const f of filings){try{const base='https://www.sec.gov/Archives/edgar/data/'+Number(cik)+'/'+f.accession.replaceAll('-','')+'/',file=f.doc.split('/').at(-1);if(!/^[\w.-]+\.xml$/i.test(file))continue;const url=base+file;const parsed=await cache(env,'sec-doc/'+f.accession,30*24*RHOUR,async()=>parseForm4(await researchFetch(url),{url,accepted:f.accepted,accession:f.accession,symbol}));if(!parsed.value)throw Error(parsed.error||'Filing unavailable');items.push(...parsed.value);}catch{errors.push(f.accession)}}
 // Any amendment makes matching owner history ambiguous; retain evidence but exclude that owner from automatic overlaps.
 const amendedOwners=new Set(items.filter(i=>i.amended).flatMap(i=>i.owners.map(o=>o.id)));for(const i of items)if(i.owners.some(o=>amendedOwners.has(o.id))){i.purchase=false;i.note+=' · owner has amendment in loaded filings; review required'}
 return observed(env,symbol,'sec',{items,company:s.name,cik,coverage:`Latest ${filings.length} Form 4/4A filings within 180 days; non-derivative transactions only. ${errors.length} filings unavailable. Not a complete insider history.`,partial:errors.length>0,url:'https://www.sec.gov/edgar/browse/?CIK='+cik});
}
export const normalizeRecipient=s=>String(s||'').toUpperCase().replace(/[^A-Z0-9 ]/g,' ').replace(/\b(CORPORATION|CORP|INCORPORATED|INC|LLC|LTD|LIMITED|CO|COMPANY)\b/g,'').replace(/\s+/g,' ').trim();
async function awardResearch(env,symbol){const company=researchUniverse[symbol]?.[0];if(!company)return {items:[],coverage:'No reviewed company search term for this ticker'};
 const body={filters:{keywords:[company],award_type_codes:['A','B','C','D','02','03','04','05'],time_period:[{start_date:ago(365),end_date:today()}]},fields:['Award ID','Recipient Name','Award Amount','Start Date','Awarding Agency','Description'],limit:20,page:1,sort:'Start Date',order:'desc'};
 // USAspending requires separate contract and assistance queries.
 const results=[];for(const types of [['A','B','C','D'],['02','03','04','05']]){const j=await rjson('https://api.usaspending.gov/api/v2/search/spending_by_award/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,filters:{...body.filters,award_type_codes:types}})});if(!Array.isArray(j.results))throw Error('Award schema changed');results.push(...j.results.map(r=>({...r,awardKind:types[0]==='A'?'Contract':'Grant'})))}
 const items=[...new Map(results.map(r=>[r.generated_internal_id,r])).values()].filter(r=>r.generated_internal_id).map(r=>({id:'award:'+r.generated_internal_id,kind:'award',symbol,title:r['Recipient Name'],description:r.Description,agency:r['Awarding Agency'],amount:r['Award Amount'],awardKind:r.awardKind,traded:r['Start Date'],published:null,url:'https://www.usaspending.gov/award/'+encodeURIComponent(r.generated_internal_id),match:normalizeRecipient(r['Recipient Name'])===normalizeRecipient(company)?'Normalized recipient name':'Keyword candidate · recipient unverified',exact:normalizeRecipient(r['Recipient Name'])===normalizeRecipient(company),note:'Obligated award amount, not company revenue. Award start is not publication date.'}));
 return observed(env,symbol,'awards',{items,coverage:'Up to 20 contracts + 20 grants with activity in the past year, searched by company name. Subsidiaries and identity are not independently resolved; keyword candidates do not count as company evidence.'});}
async function policyResearch(env,symbol){const term=researchUniverse[symbol]?.[1];if(!term)return {items:[],coverage:'No reviewed policy keyword for this ticker'};
 const j=await rjson('https://www.federalregister.gov/api/v1/documents.json?per_page=12&order=newest&conditions[publication_date][gte]='+ago(90)+'&conditions[term]='+encodeURIComponent(term));if(!Array.isArray(j.results))throw Error('Policy source unavailable');
 return observed(env,symbol,'policy',{items:j.results.map(r=>({id:'fr:'+r.document_number,kind:'policy',symbol,title:r.title,published:r.publication_date,traded:r.effective_on||null,url:r.html_url,documentType:r.type,agency:(r.agencies||[]).map(a=>a.name).join(', '),match:'Sector keyword: '+term,note:'Research candidate; company impact and direction unverified.'})),coverage:'Latest 12 sector-keyword matches published within 90 days. Proposed rules are not final rules.'});}
async function billResearch(env,symbol){if(!env.CONGRESS_API_KEY)return {items:[],unavailable:true,coverage:'Congress.gov API key required. Bill and committee matching is not connected.'};
 const term=researchUniverse[symbol]?.[1];if(!term)return {items:[],coverage:'No policy keyword configured'};
 const j=await rjson('https://api.congress.gov/v3/bill?format=json&limit=250&sort=updateDate+desc&api_key='+encodeURIComponent(env.CONGRESS_API_KEY));if(!Array.isArray(j.bills))throw Error('Congress.gov unavailable');
 const words=term==='semiconductors'?/semiconductor|chips/i:new RegExp(term,'i');const found=j.bills.filter(b=>['HR','S'].includes(b.type)&&words.test(b.title));const items=[];
 for(const b of found.slice(0,5)){const committees=await rjson(`https://api.congress.gov/v3/bill/${b.congress}/${b.type.toLowerCase()}/${b.number}/committees?format=json&api_key=${encodeURIComponent(env.CONGRESS_API_KEY)}`);items.push({id:`bill:${b.congress}:${b.type}:${b.number}`,kind:'bill',symbol,title:b.title,published:b.latestAction?.actionDate||null,traded:b.latestAction?.actionDate||null,url:`https://www.congress.gov/bill/${b.congress}th-congress/${b.type==='S'?'senate':'house'}-bill/${b.number}`,match:'Title keyword candidate',note:b.latestAction?.text,committees:(committees.committees||[]).map(c=>c.name)})}
 return observed(env,symbol,'bills',{items,coverage:'Keyword scan of the 250 most recently updated bills; committee referrals shown, not politician influence or verified company impact.'});}
async function earningsResearch(env,symbol,cache){if(!env.ALPHA_VANTAGE_API_KEY)return {items:[],unavailable:true,coverage:'Earnings feed needs an Alpha Vantage API key; no date is assumed.'};
 const all=await cache(env,'earnings-calendar-v1',24*RHOUR,async()=>({rows:parseCalendar(await researchFetch('https://www.alphavantage.co/query?function=EARNINGS_CALENDAR&horizon=3month&apikey='+encodeURIComponent(env.ALPHA_VANTAGE_API_KEY)))}));if(!all.value||all.stale)throw Error('Earnings provider unavailable');const items=all.value.rows.filter(r=>r.symbol===symbol&&r.reportDate>=today()).map(r=>({id:'earnings:'+symbol+':'+r.reportDate,kind:'earnings',symbol,title:'Expected earnings',traded:r.reportDate,published:null,url:'https://www.alphavantage.co/documentation/#earnings-calendar',match:'Provider ticker',note:'Expected date; confirm with investor relations. Release time not supplied.',currency:r.currency}));return {...await observed(env,symbol,'earnings',{items,coverage:items.length?'3-month provider calendar; dates can change.':'No date found in the next 3 months; this does not establish there is no earnings risk.'}),stale:all.stale};}
export async function researchRoute(url,env,cache){const path=url.pathname;if(path==='/api/research/treasury')return cache(env,'treasury-v1',6*RHOUR,async()=>{const year=new Date().getUTCFullYear(),xml=await researchFetch('https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml?data=daily_treasury_yield_curve&field_tdr_date_value='+year);return parseTreasury(xml)});
 if(path==='/api/research/status'){const o=await env.BUCKET.get('poor/research/collector');return {collector:o?await o.json():null,congressConnected:!!env.CONGRESS_API_KEY,earningsConnected:!!env.ALPHA_VANTAGE_API_KEY}}
 const symbol=url.searchParams.get('symbol');if(!/^[A-Z][A-Z0-9.-]{0,11}$/.test(symbol||''))return {error:'Invalid ticker'};
 if(path==='/api/research/signals')return evidenceSignals(env,symbol);
 if(path==='/api/research/agent'){const o=await env.BUCKET.get('poor/research/agent/'+symbol);return o?await o.json():{items:[],coverage:'No Hermes research received yet.'}}
 const source=url.searchParams.get('source');const loaders={sec:()=>secResearch(env,symbol,cache),awards:()=>awardResearch(env,symbol),policy:()=>policyResearch(env,symbol),bills:()=>billResearch(env,symbol),earnings:()=>earningsResearch(env,symbol,cache)};if(!loaders[source])return {error:'Unknown research source'};
 return cache(env,'research-v1/'+symbol+'/'+source,6*RHOUR,loaders[source]);}
export function connectionSignals(politics,insiders){
 const purchases=politics.filter(r=>r.type==='Purchase'&&['Stock','ADR','Call options'].includes(r.asset)&&day(r.traded)&&day(r.filed));const candidates=[];
 for(const anchor of [...purchases,...insiders.filter(r=>r.purchase)]){const end=new Date(Date.parse(anchor.traded)+30*86400000).toISOString().slice(0,10),p=purchases.filter(r=>r.traded>=anchor.traded&&r.traded<=end),i=insiders.filter(r=>r.purchase&&r.traded>=anchor.traded&&r.traded<=end);const people=[...new Set(p.map(r=>r.person))].sort(),owners=[...new Set(i.flatMap(r=>r.owners.map(o=>o.id)).filter(Boolean))];if(people.length<2&&!(people.length&&owners.length))continue;
 const docs=[...new Set([...p.map(r=>r.source),...i.map(r=>r.url)])].sort(),key=docs.join('|');if(candidates.some(c=>c.key===key))continue;candidates.push({key,politicians:people,insiderOwners:owners.length,start:anchor.traded,end:[...p.map(r=>r.traded),...i.map(r=>r.traded)].sort().at(-1),publicBy:[...p.map(r=>r.filed),...i.map(r=>(r.published||'').slice(0,10))].sort().at(-1),sources:docs,families:owners.length?2:1});}
 return candidates.sort((a,b)=>b.politicians.length+b.insiderOwners-a.politicians.length-a.insiderOwners).slice(0,10);
}
export function forwardResult(closes,observedAt,horizon){const dates=Object.keys(closes||{}).filter(day).sort(),start=dates.findIndex(d=>d>observedAt.slice(0,10));if(start<0||!dates[start+horizon])return null;const end=start+horizon,a=closes[dates[start]],b=closes[dates[end]];return a>0&&b>0?{entry:dates[start],end:dates[end],return:(b/a-1)*100}:null;}
async function evidenceSignals(env,symbol){const read=async key=>{const o=await env.BUCKET.get(key);return o?await o.json():null};const [congress,sec,history,price,spy]=await Promise.all([read('pif/v1/congress-roster-v1'),read('pif/v1/research-v1/'+symbol+'/sec'),read('poor/research/signals/'+symbol),read('pif/v1/prices-v3/'+symbol),read('pif/v1/prices-v3/SPY')]);
 const inputsCurrent=[congress,sec].every(x=>x?.value&&!x.error&&!x.value.partial&&Date.now()-x.checkedAt<7*RHOUR),found=inputsCurrent?connectionSignals((congress?.value?.rows||[]).filter(r=>r.ticker===symbol&&r.traded>=ago(180)),sec?.value?.items||[]):[],records=history?.records||[];
 for(const c of found){const id=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(c.key)))).map(v=>v.toString(16).padStart(2,'0')).join('');if(!records.some(r=>r.id===id))records.push({...c,key:undefined,id,symbol,firstObserved:new Date().toISOString()})}
 const stored=records.slice(-300);if(found.length)await env.BUCKET.put('poor/research/signals/'+symbol,JSON.stringify({records:stored}));
 return {items:stored.map(r=>({...r,forward:[5,20,60].map(n=>{const ret=forwardResult(price?.value?.closes,r.firstObserved,n);const a=ret&&spy?.value?.closes?.[ret.entry],b=ret&&spy?.value?.closes?.[ret.end];return {sessions:n,...ret,excess:ret&&a>0&&b>0?ret.return-(b/a-1)*100:null}})})).reverse(),inputsCurrent,coverage:'30-calendar-day buying windows. One count per politician household; SEC owners counted separately. Forward tracking begins at the first close strictly after poor first observed the combination. 5/20/60-session returns exclude dividends, fees and execution costs. Overlapping windows are not independent samples; no probability of insider knowledge is inferred.'};}
export async function researchIngest(request,env){
 const token=request.headers.get('Authorization');if(!env.RESEARCH_INGEST_TOKEN||token!=='Bearer '+env.RESEARCH_INGEST_TOKEN)return {status:401,body:{error:'Unauthorized'}};
 if(!(request.headers.get('Content-Type')||'').startsWith('application/json'))return {status:415,body:{error:'JSON required'}};const text=await request.text();if(text.length>100000)return {status:413,body:{error:'Too large'}};let b;try{b=JSON.parse(text)}catch{return {status:400,body:{error:'Invalid JSON'}}}
 if(b.kind==='collector'){const status={lastRun:new Date().toISOString(),successful:Number(b.successful)||0,failed:Number(b.failed)||0,schedule:'Every 6 hours while this PC is awake and you are signed in'};await env.BUCKET.put('poor/research/collector',JSON.stringify(status));return {status:200,body:{ok:true}}}
 if(b.kind!=='agent'||!/^[A-Z][A-Z0-9.-]{0,11}$/.test(b.symbol||'')||!Array.isArray(b.items)||b.items.length>12)return {status:400,body:{error:'Invalid report'}};
 const items=b.items.map(r=>({title:String(r.title||'').slice(0,200),summary:String(r.summary||'').slice(0,1200),url:String(r.url||''),published:day(r.published)?r.published:null,firstObserved:new Date().toISOString(),kind:'agent',match:'Hermes research · unverified inference'}));if(items.some(r=>!r.title||!/^https:\/\//.test(r.url)||r.url.length>1500))return {status:400,body:{error:'Reports need HTTPS source links'}};
 await env.BUCKET.put('poor/research/agent/'+b.symbol,JSON.stringify({items,updatedAt:new Date().toISOString(),coverage:'Hermes/Grok research leads. Claims require primary-source verification; not counted in purchase signals.'}));return {status:200,body:{ok:true}};
}
